name: Release

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
        default: 'main'
      increment-version:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to be used'
        type: string
        required: false
        default: 'main'
      increment-version:
        description: 'Increment version'
        type: boolean
        required: false
        default: false

jobs:
  release:
    uses: coditory/workflows/.github/workflows/release-action.yml@v1
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
      increment-version: ${{ inputs.increment-version }}
