name: Release Auto

on:
  workflow_dispatch:
  schedule:
    # at 5:30 UTC every month
    - cron: "30 5 1 * *"

jobs:
  check:
    uses: coditory/workflows/.github/workflows/release-check.yml@v1
    secrets: inherit

  auto-release:
    uses: ./.github/workflows/release.yml
    secrets: inherit
    if: needs.check.outputs.release == 'true'
    needs: check

